version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      args:
        - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/db
      - PORT=5000
      - ACCESS_TOKEN_SECRET=ygjhug65876ufg45765utyfhgtyuu
      - WAIT_HOSTS=postgres:5432
    depends_on:
        - postgres
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm run prod'
    ports:
      - 5000:5000
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - REACT_APP_API_URI=http://139.59.9.38:5000
    ports:
      - 80:80
    depends_on:
      - api
